# Project Euler Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# Code below

a = 1; b = 1; c = 0; list = [1]; list2 = []	

while a < 4000000:
	c = a + b 
	list.append(c)
	a = b
	b = c
		
for i in list:
		if i%2 == 0:
			list2.append(i)
			
sum(list2)