## Problem 45

## Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
## Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
## Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
## Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

## It can be verified that T285 = P165 = H143 = 40755.

## Find the next triangle number that is also pentagonal and hexagonal.

# function to triangle-pentagonal-hexagonal number
def T_P_H():

	import timeit # import timeit and start timer to measure time of function
	start = timeit.default_timer()
	
	for i in range(286,99999): # start at 286 per problem - upper bound is unknown
	
		if is_Pent(i*(i+1)/2) and is_Hex(i*(i+1)/2):
			
			print i*(i+1)/2
	
	# stop timer and print total elapsed time
	stop = timeit.default_timer()
	print "Total time:", stop - start 			

# function to determine whether number is pentagonal
def is_Pent(n):	
	
	if (((24*n+1)**.5+1) / 6).is_integer():
		return True
	
	else:
		return False
	
# function to determine whether number is hexagonal	
def is_Hex(n):	
	
	if (((8*n+1)**.5+1) / 4).is_integer():
		return True
	
	else:
		return False